/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IWeaveRewards,
  IWeaveRewardsInterface,
} from "../../../contracts/WeaveVault.sol/IWeaveRewards";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "usdcAmount",
        type: "uint256",
      },
    ],
    name: "distributeRewards",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IWeaveRewards__factory {
  static readonly abi = _abi;
  static createInterface(): IWeaveRewardsInterface {
    return new Interface(_abi) as IWeaveRewardsInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IWeaveRewards {
    return new Contract(address, _abi, runner) as unknown as IWeaveRewards;
  }
}
