/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IWeaveVault,
  IWeaveVaultInterface,
} from "../../../contracts/WeaveZapIn.sol/IWeaveVault";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "user",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "depositFor",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "depositToken",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IWeaveVault__factory {
  static readonly abi = _abi;
  static createInterface(): IWeaveVaultInterface {
    return new Interface(_abi) as IWeaveVaultInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): IWeaveVault {
    return new Contract(address, _abi, runner) as unknown as IWeaveVault;
  }
}
