/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IVeWeave__factory } from "./IVeWeave__factory";
export { WeaveGauge__factory } from "./WeaveGauge__factory";
