/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IBlackwing,
  IBlackwingInterface,
} from "../../../../contracts/strategies/BlackwingStrategy.sol/IBlackwing";

const _abi = [
  {
    inputs: [],
    name: "claimRewards",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "deposit",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "user",
        type: "address",
      },
    ],
    name: "pendingRewards",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "withdraw",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IBlackwing__factory {
  static readonly abi = _abi;
  static createInterface(): IBlackwingInterface {
    return new Interface(_abi) as IBlackwingInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): IBlackwing {
    return new Contract(address, _abi, runner) as unknown as IBlackwing;
  }
}
