/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { BlackwingStrategy__factory } from "./BlackwingStrategy__factory";
export { IBlackwing__factory } from "./IBlackwing__factory";
