/* eslint-disable */
/**
 * Generated API definitions.
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * Generated by convex@1.14.0.
 * To regenerate, run `npx convex dev`.
 * @module
 */

import type {
    ApiFromModules,
    FilterApi,
    FunctionReference,
} from "convex/server";
import type * as crons from "../crons.js";
import type * as faucet from "../faucet.js";
import type * as functions from "../functions.js";

/**
 * A type describing your app's public Convex API.
 *
 * This `api` export is used with `useQuery` and `useMutation` to HTTP
 * endpoint calls.
 *
 * The type is valid JavaScript value, but it's also a type that
 * declares the shape of your query and mutation definitions.
 */
declare const fullApi: ApiFromModules<{
    crons: typeof crons;
    faucet: typeof faucet;
    functions: typeof functions;
}>;
export declare const api: FilterApi<
    fullApi,
    FunctionReference<any, "public">
>;
export default api;
