/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as weaveZapInSol from "./WeaveZapIn.sol";
export type { weaveZapInSol };
export type { MockERC20 } from "./MockERC20";
export type { WeaveVault } from "./WeaveVault";
