/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as weaveGaugeSol from "./WeaveGauge.sol";
export type { weaveGaugeSol };
import type * as weaveRewardsSol from "./WeaveRewards.sol";
export type { weaveRewardsSol };
import type * as weaveVaultSol from "./WeaveVault.sol";
export type { weaveVaultSol };
import type * as weaveZapInSol from "./WeaveZapIn.sol";
export type { weaveZapInSol };
export type { MockERC20 } from "./MockERC20";
export type { VeWeave } from "./VeWeave";
export type { WeaveToken } from "./WeaveToken";
export type { WeaveVesting } from "./WeaveVesting";
