/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace VeWeave {
  export type LockPositionStruct = {
    amount: BigNumberish;
    lockEnd: BigNumberish;
    veBalance: BigNumberish;
  };

  export type LockPositionStructOutput = [
    amount: bigint,
    lockEnd: bigint,
    veBalance: bigint
  ] & { amount: bigint; lockEnd: bigint; veBalance: bigint };
}

export interface VeWeaveInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "durations"
      | "getTotalVotingPower"
      | "getUserLock"
      | "getVotingPower"
      | "lock"
      | "locks"
      | "multipliers"
      | "totalVeSupply"
      | "transfer"
      | "transferFrom"
      | "unlock"
      | "weaveToken"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "LockExtended" | "Locked" | "Unlocked"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "durations",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getTotalVotingPower",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getUserLock",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getVotingPower",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "lock",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "locks", values: [AddressLike]): string;
  encodeFunctionData(
    functionFragment: "multipliers",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "totalVeSupply",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transfer",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferFrom",
    values: [AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "unlock", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "weaveToken",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "durations", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getTotalVotingPower",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserLock",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getVotingPower",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "lock", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "locks", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "multipliers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalVeSupply",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "transfer", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferFrom",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unlock", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "weaveToken", data: BytesLike): Result;
}

export namespace LockExtendedEvent {
  export type InputTuple = [user: AddressLike, newDuration: BigNumberish];
  export type OutputTuple = [user: string, newDuration: bigint];
  export interface OutputObject {
    user: string;
    newDuration: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LockedEvent {
  export type InputTuple = [
    user: AddressLike,
    amount: BigNumberish,
    duration: BigNumberish,
    veBalance: BigNumberish
  ];
  export type OutputTuple = [
    user: string,
    amount: bigint,
    duration: bigint,
    veBalance: bigint
  ];
  export interface OutputObject {
    user: string;
    amount: bigint;
    duration: bigint;
    veBalance: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnlockedEvent {
  export type InputTuple = [user: AddressLike, amount: BigNumberish];
  export type OutputTuple = [user: string, amount: bigint];
  export interface OutputObject {
    user: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface VeWeave extends BaseContract {
  connect(runner?: ContractRunner | null): VeWeave;
  waitForDeployment(): Promise<this>;

  interface: VeWeaveInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  durations: TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;

  getTotalVotingPower: TypedContractMethod<[], [bigint], "view">;

  getUserLock: TypedContractMethod<
    [user: AddressLike],
    [VeWeave.LockPositionStructOutput],
    "view"
  >;

  getVotingPower: TypedContractMethod<[user: AddressLike], [bigint], "view">;

  lock: TypedContractMethod<
    [amount: BigNumberish, durationIndex: BigNumberish],
    [void],
    "nonpayable"
  >;

  locks: TypedContractMethod<
    [arg0: AddressLike],
    [
      [bigint, bigint, bigint] & {
        amount: bigint;
        lockEnd: bigint;
        veBalance: bigint;
      }
    ],
    "view"
  >;

  multipliers: TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;

  totalVeSupply: TypedContractMethod<[], [bigint], "view">;

  transfer: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [boolean],
    "view"
  >;

  transferFrom: TypedContractMethod<
    [arg0: AddressLike, arg1: AddressLike, arg2: BigNumberish],
    [boolean],
    "view"
  >;

  unlock: TypedContractMethod<[], [void], "nonpayable">;

  weaveToken: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "durations"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "getTotalVotingPower"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getUserLock"
  ): TypedContractMethod<
    [user: AddressLike],
    [VeWeave.LockPositionStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getVotingPower"
  ): TypedContractMethod<[user: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "lock"
  ): TypedContractMethod<
    [amount: BigNumberish, durationIndex: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "locks"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [bigint, bigint, bigint] & {
        amount: bigint;
        lockEnd: bigint;
        veBalance: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "multipliers"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalVeSupply"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "transfer"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "transferFrom"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: AddressLike, arg2: BigNumberish],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "unlock"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "weaveToken"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "LockExtended"
  ): TypedContractEvent<
    LockExtendedEvent.InputTuple,
    LockExtendedEvent.OutputTuple,
    LockExtendedEvent.OutputObject
  >;
  getEvent(
    key: "Locked"
  ): TypedContractEvent<
    LockedEvent.InputTuple,
    LockedEvent.OutputTuple,
    LockedEvent.OutputObject
  >;
  getEvent(
    key: "Unlocked"
  ): TypedContractEvent<
    UnlockedEvent.InputTuple,
    UnlockedEvent.OutputTuple,
    UnlockedEvent.OutputObject
  >;

  filters: {
    "LockExtended(address,uint256)": TypedContractEvent<
      LockExtendedEvent.InputTuple,
      LockExtendedEvent.OutputTuple,
      LockExtendedEvent.OutputObject
    >;
    LockExtended: TypedContractEvent<
      LockExtendedEvent.InputTuple,
      LockExtendedEvent.OutputTuple,
      LockExtendedEvent.OutputObject
    >;

    "Locked(address,uint256,uint256,uint256)": TypedContractEvent<
      LockedEvent.InputTuple,
      LockedEvent.OutputTuple,
      LockedEvent.OutputObject
    >;
    Locked: TypedContractEvent<
      LockedEvent.InputTuple,
      LockedEvent.OutputTuple,
      LockedEvent.OutputObject
    >;

    "Unlocked(address,uint256)": TypedContractEvent<
      UnlockedEvent.InputTuple,
      UnlockedEvent.OutputTuple,
      UnlockedEvent.OutputObject
    >;
    Unlocked: TypedContractEvent<
      UnlockedEvent.InputTuple,
      UnlockedEvent.OutputTuple,
      UnlockedEvent.OutputObject
    >;
  };
}
