/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace WeaveGauge {
  export type GaugeStruct = {
    name: string;
    strategy: AddressLike;
    totalVotes: BigNumberish;
    allocation: BigNumberish;
  };

  export type GaugeStructOutput = [
    name: string,
    strategy: string,
    totalVotes: bigint,
    allocation: bigint
  ] & {
    name: string;
    strategy: string;
    totalVotes: bigint;
    allocation: bigint;
  };
}

export interface WeaveGaugeInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "EPOCH_DURATION"
      | "addGauge"
      | "epochEnd"
      | "finalizeEpoch"
      | "gauges"
      | "getGauge"
      | "getGaugeCount"
      | "owner"
      | "renounceOwnership"
      | "transferOwnership"
      | "userVotes"
      | "veWeave"
      | "vote"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "EpochFinalized"
      | "GaugeAdded"
      | "OwnershipTransferred"
      | "Voted"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "EPOCH_DURATION",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "addGauge",
    values: [string, AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "epochEnd", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "finalizeEpoch",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "gauges",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getGauge",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getGaugeCount",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "userVotes",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "veWeave", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "vote",
    values: [BigNumberish, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "EPOCH_DURATION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "addGauge", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "epochEnd", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "finalizeEpoch",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "gauges", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getGauge", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getGaugeCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "userVotes", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "veWeave", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "vote", data: BytesLike): Result;
}

export namespace EpochFinalizedEvent {
  export type InputTuple = [allocations: BigNumberish[]];
  export type OutputTuple = [allocations: bigint[]];
  export interface OutputObject {
    allocations: bigint[];
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace GaugeAddedEvent {
  export type InputTuple = [name: string, strategy: AddressLike];
  export type OutputTuple = [name: string, strategy: string];
  export interface OutputObject {
    name: string;
    strategy: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VotedEvent {
  export type InputTuple = [
    user: AddressLike,
    gaugeId: BigNumberish,
    amount: BigNumberish
  ];
  export type OutputTuple = [user: string, gaugeId: bigint, amount: bigint];
  export interface OutputObject {
    user: string;
    gaugeId: bigint;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface WeaveGauge extends BaseContract {
  connect(runner?: ContractRunner | null): WeaveGauge;
  waitForDeployment(): Promise<this>;

  interface: WeaveGaugeInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  EPOCH_DURATION: TypedContractMethod<[], [bigint], "view">;

  addGauge: TypedContractMethod<
    [name: string, strategy: AddressLike],
    [void],
    "nonpayable"
  >;

  epochEnd: TypedContractMethod<[], [bigint], "view">;

  finalizeEpoch: TypedContractMethod<[], [void], "nonpayable">;

  gauges: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, bigint, bigint] & {
        name: string;
        strategy: string;
        totalVotes: bigint;
        allocation: bigint;
      }
    ],
    "view"
  >;

  getGauge: TypedContractMethod<
    [id: BigNumberish],
    [WeaveGauge.GaugeStructOutput],
    "view"
  >;

  getGaugeCount: TypedContractMethod<[], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  userVotes: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  veWeave: TypedContractMethod<[], [string], "view">;

  vote: TypedContractMethod<
    [gaugeId: BigNumberish, veAmount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "EPOCH_DURATION"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "addGauge"
  ): TypedContractMethod<
    [name: string, strategy: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "epochEnd"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "finalizeEpoch"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "gauges"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, bigint, bigint] & {
        name: string;
        strategy: string;
        totalVotes: bigint;
        allocation: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getGauge"
  ): TypedContractMethod<
    [id: BigNumberish],
    [WeaveGauge.GaugeStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getGaugeCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "userVotes"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "veWeave"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "vote"
  ): TypedContractMethod<
    [gaugeId: BigNumberish, veAmount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "EpochFinalized"
  ): TypedContractEvent<
    EpochFinalizedEvent.InputTuple,
    EpochFinalizedEvent.OutputTuple,
    EpochFinalizedEvent.OutputObject
  >;
  getEvent(
    key: "GaugeAdded"
  ): TypedContractEvent<
    GaugeAddedEvent.InputTuple,
    GaugeAddedEvent.OutputTuple,
    GaugeAddedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "Voted"
  ): TypedContractEvent<
    VotedEvent.InputTuple,
    VotedEvent.OutputTuple,
    VotedEvent.OutputObject
  >;

  filters: {
    "EpochFinalized(uint256[])": TypedContractEvent<
      EpochFinalizedEvent.InputTuple,
      EpochFinalizedEvent.OutputTuple,
      EpochFinalizedEvent.OutputObject
    >;
    EpochFinalized: TypedContractEvent<
      EpochFinalizedEvent.InputTuple,
      EpochFinalizedEvent.OutputTuple,
      EpochFinalizedEvent.OutputObject
    >;

    "GaugeAdded(string,address)": TypedContractEvent<
      GaugeAddedEvent.InputTuple,
      GaugeAddedEvent.OutputTuple,
      GaugeAddedEvent.OutputObject
    >;
    GaugeAdded: TypedContractEvent<
      GaugeAddedEvent.InputTuple,
      GaugeAddedEvent.OutputTuple,
      GaugeAddedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "Voted(address,uint256,uint256)": TypedContractEvent<
      VotedEvent.InputTuple,
      VotedEvent.OutputTuple,
      VotedEvent.OutputObject
    >;
    Voted: TypedContractEvent<
      VotedEvent.InputTuple,
      VotedEvent.OutputTuple,
      VotedEvent.OutputObject
    >;
  };
}
