/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { ITucana__factory } from "./ITucana__factory";
export { TucanaStrategy__factory } from "./TucanaStrategy__factory";
