/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as blackwingStrategySol from "./BlackwingStrategy.sol";
export * as tucanaStrategySol from "./TucanaStrategy.sol";
export { MockProtocol__factory } from "./MockProtocol__factory";
