/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { BlackwingStrategy } from "./BlackwingStrategy";
export type { IBlackwing } from "./IBlackwing";
