/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ethers } from "ethers";
import {
  DeployContractOptions,
  FactoryOptions,
  HardhatEthersHelpers as HardhatEthersHelpersBase,
} from "@nomicfoundation/hardhat-ethers/types";

import * as Contracts from ".";

declare module "hardhat/types/runtime" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
    getContractFactory(
      name: "Ownable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Ownable__factory>;
    getContractFactory(
      name: "IERC1155Errors",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC1155Errors__factory>;
    getContractFactory(
      name: "IERC20Errors",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC20Errors__factory>;
    getContractFactory(
      name: "IERC721Errors",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC721Errors__factory>;
    getContractFactory(
      name: "IERC1363",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC1363__factory>;
    getContractFactory(
      name: "ERC20",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ERC20__factory>;
    getContractFactory(
      name: "IERC20Metadata",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC20Metadata__factory>;
    getContractFactory(
      name: "IERC20",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC20__factory>;
    getContractFactory(
      name: "SafeERC20",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.SafeERC20__factory>;
    getContractFactory(
      name: "IERC165",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC165__factory>;
    getContractFactory(
      name: "Pausable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Pausable__factory>;
    getContractFactory(
      name: "ReentrancyGuard",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ReentrancyGuard__factory>;
    getContractFactory(
      name: "CrossMinitiaRouter",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.CrossMinitiaRouter__factory>;
    getContractFactory(
      name: "IStrategy",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IStrategy__factory>;
    getContractFactory(
      name: "IWeavifyStrategy",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IWeavifyStrategy__factory>;
    getContractFactory(
      name: "MockERC20",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.MockERC20__factory>;
    getContractFactory(
      name: "BlackwingStrategy",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.BlackwingStrategy__factory>;
    getContractFactory(
      name: "IBlackwing",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IBlackwing__factory>;
    getContractFactory(
      name: "EchelonStrategy",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.EchelonStrategy__factory>;
    getContractFactory(
      name: "IEchelonMarket",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IEchelonMarket__factory>;
    getContractFactory(
      name: "InitiaDEXStrategy",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.InitiaDEXStrategy__factory>;
    getContractFactory(
      name: "MockProtocol",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.MockProtocol__factory>;
    getContractFactory(
      name: "StableLPStrategy",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.StableLPStrategy__factory>;
    getContractFactory(
      name: "ITucana",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ITucana__factory>;
    getContractFactory(
      name: "TucanaStrategy",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.TucanaStrategy__factory>;
    getContractFactory(
      name: "VeWeave",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.VeWeave__factory>;
    getContractFactory(
      name: "VIPScore",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.VIPScore__factory>;
    getContractFactory(
      name: "IVeWeave",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IVeWeave__factory>;
    getContractFactory(
      name: "WeaveGauge",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.WeaveGauge__factory>;
    getContractFactory(
      name: "IVeWeave",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IVeWeave__factory>;
    getContractFactory(
      name: "WeaveRewards",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.WeaveRewards__factory>;
    getContractFactory(
      name: "WeaveToken",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.WeaveToken__factory>;
    getContractFactory(
      name: "IInitiaDEX",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IInitiaDEX__factory>;
    getContractFactory(
      name: "IWeaveRewards",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IWeaveRewards__factory>;
    getContractFactory(
      name: "WeaveVault",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.WeaveVault__factory>;
    getContractFactory(
      name: "WeaveVesting",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.WeaveVesting__factory>;
    getContractFactory(
      name: "IWeaveVault",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IWeaveVault__factory>;
    getContractFactory(
      name: "WeaveZapIn",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.WeaveZapIn__factory>;

    getContractAt(
      name: "Ownable",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.Ownable>;
    getContractAt(
      name: "IERC1155Errors",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC1155Errors>;
    getContractAt(
      name: "IERC20Errors",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC20Errors>;
    getContractAt(
      name: "IERC721Errors",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC721Errors>;
    getContractAt(
      name: "IERC1363",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC1363>;
    getContractAt(
      name: "ERC20",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ERC20>;
    getContractAt(
      name: "IERC20Metadata",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC20Metadata>;
    getContractAt(
      name: "IERC20",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC20>;
    getContractAt(
      name: "SafeERC20",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.SafeERC20>;
    getContractAt(
      name: "IERC165",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC165>;
    getContractAt(
      name: "Pausable",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.Pausable>;
    getContractAt(
      name: "ReentrancyGuard",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ReentrancyGuard>;
    getContractAt(
      name: "CrossMinitiaRouter",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.CrossMinitiaRouter>;
    getContractAt(
      name: "IStrategy",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IStrategy>;
    getContractAt(
      name: "IWeavifyStrategy",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IWeavifyStrategy>;
    getContractAt(
      name: "MockERC20",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.MockERC20>;
    getContractAt(
      name: "BlackwingStrategy",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.BlackwingStrategy>;
    getContractAt(
      name: "IBlackwing",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IBlackwing>;
    getContractAt(
      name: "EchelonStrategy",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.EchelonStrategy>;
    getContractAt(
      name: "IEchelonMarket",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IEchelonMarket>;
    getContractAt(
      name: "InitiaDEXStrategy",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.InitiaDEXStrategy>;
    getContractAt(
      name: "MockProtocol",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.MockProtocol>;
    getContractAt(
      name: "StableLPStrategy",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.StableLPStrategy>;
    getContractAt(
      name: "ITucana",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ITucana>;
    getContractAt(
      name: "TucanaStrategy",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.TucanaStrategy>;
    getContractAt(
      name: "VeWeave",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.VeWeave>;
    getContractAt(
      name: "VIPScore",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.VIPScore>;
    getContractAt(
      name: "IVeWeave",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IVeWeave>;
    getContractAt(
      name: "WeaveGauge",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.WeaveGauge>;
    getContractAt(
      name: "IVeWeave",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IVeWeave>;
    getContractAt(
      name: "WeaveRewards",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.WeaveRewards>;
    getContractAt(
      name: "WeaveToken",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.WeaveToken>;
    getContractAt(
      name: "IInitiaDEX",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IInitiaDEX>;
    getContractAt(
      name: "IWeaveRewards",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IWeaveRewards>;
    getContractAt(
      name: "WeaveVault",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.WeaveVault>;
    getContractAt(
      name: "WeaveVesting",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.WeaveVesting>;
    getContractAt(
      name: "IWeaveVault",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IWeaveVault>;
    getContractAt(
      name: "WeaveZapIn",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.WeaveZapIn>;

    deployContract(
      name: "Ownable",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Ownable>;
    deployContract(
      name: "IERC1155Errors",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC1155Errors>;
    deployContract(
      name: "IERC20Errors",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC20Errors>;
    deployContract(
      name: "IERC721Errors",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC721Errors>;
    deployContract(
      name: "IERC1363",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC1363>;
    deployContract(
      name: "ERC20",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ERC20>;
    deployContract(
      name: "IERC20Metadata",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC20Metadata>;
    deployContract(
      name: "IERC20",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC20>;
    deployContract(
      name: "SafeERC20",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.SafeERC20>;
    deployContract(
      name: "IERC165",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC165>;
    deployContract(
      name: "Pausable",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Pausable>;
    deployContract(
      name: "ReentrancyGuard",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ReentrancyGuard>;
    deployContract(
      name: "CrossMinitiaRouter",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.CrossMinitiaRouter>;
    deployContract(
      name: "IStrategy",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IStrategy>;
    deployContract(
      name: "IWeavifyStrategy",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IWeavifyStrategy>;
    deployContract(
      name: "MockERC20",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MockERC20>;
    deployContract(
      name: "BlackwingStrategy",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.BlackwingStrategy>;
    deployContract(
      name: "IBlackwing",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IBlackwing>;
    deployContract(
      name: "EchelonStrategy",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.EchelonStrategy>;
    deployContract(
      name: "IEchelonMarket",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IEchelonMarket>;
    deployContract(
      name: "InitiaDEXStrategy",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.InitiaDEXStrategy>;
    deployContract(
      name: "MockProtocol",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MockProtocol>;
    deployContract(
      name: "StableLPStrategy",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.StableLPStrategy>;
    deployContract(
      name: "ITucana",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ITucana>;
    deployContract(
      name: "TucanaStrategy",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.TucanaStrategy>;
    deployContract(
      name: "VeWeave",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.VeWeave>;
    deployContract(
      name: "VIPScore",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.VIPScore>;
    deployContract(
      name: "IVeWeave",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IVeWeave>;
    deployContract(
      name: "WeaveGauge",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.WeaveGauge>;
    deployContract(
      name: "IVeWeave",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IVeWeave>;
    deployContract(
      name: "WeaveRewards",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.WeaveRewards>;
    deployContract(
      name: "WeaveToken",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.WeaveToken>;
    deployContract(
      name: "IInitiaDEX",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IInitiaDEX>;
    deployContract(
      name: "IWeaveRewards",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IWeaveRewards>;
    deployContract(
      name: "WeaveVault",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.WeaveVault>;
    deployContract(
      name: "WeaveVesting",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.WeaveVesting>;
    deployContract(
      name: "IWeaveVault",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IWeaveVault>;
    deployContract(
      name: "WeaveZapIn",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.WeaveZapIn>;

    deployContract(
      name: "Ownable",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Ownable>;
    deployContract(
      name: "IERC1155Errors",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC1155Errors>;
    deployContract(
      name: "IERC20Errors",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC20Errors>;
    deployContract(
      name: "IERC721Errors",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC721Errors>;
    deployContract(
      name: "IERC1363",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC1363>;
    deployContract(
      name: "ERC20",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ERC20>;
    deployContract(
      name: "IERC20Metadata",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC20Metadata>;
    deployContract(
      name: "IERC20",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC20>;
    deployContract(
      name: "SafeERC20",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.SafeERC20>;
    deployContract(
      name: "IERC165",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC165>;
    deployContract(
      name: "Pausable",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Pausable>;
    deployContract(
      name: "ReentrancyGuard",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ReentrancyGuard>;
    deployContract(
      name: "CrossMinitiaRouter",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.CrossMinitiaRouter>;
    deployContract(
      name: "IStrategy",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IStrategy>;
    deployContract(
      name: "IWeavifyStrategy",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IWeavifyStrategy>;
    deployContract(
      name: "MockERC20",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MockERC20>;
    deployContract(
      name: "BlackwingStrategy",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.BlackwingStrategy>;
    deployContract(
      name: "IBlackwing",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IBlackwing>;
    deployContract(
      name: "EchelonStrategy",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.EchelonStrategy>;
    deployContract(
      name: "IEchelonMarket",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IEchelonMarket>;
    deployContract(
      name: "InitiaDEXStrategy",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.InitiaDEXStrategy>;
    deployContract(
      name: "MockProtocol",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MockProtocol>;
    deployContract(
      name: "StableLPStrategy",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.StableLPStrategy>;
    deployContract(
      name: "ITucana",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ITucana>;
    deployContract(
      name: "TucanaStrategy",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.TucanaStrategy>;
    deployContract(
      name: "VeWeave",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.VeWeave>;
    deployContract(
      name: "VIPScore",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.VIPScore>;
    deployContract(
      name: "IVeWeave",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IVeWeave>;
    deployContract(
      name: "WeaveGauge",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.WeaveGauge>;
    deployContract(
      name: "IVeWeave",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IVeWeave>;
    deployContract(
      name: "WeaveRewards",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.WeaveRewards>;
    deployContract(
      name: "WeaveToken",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.WeaveToken>;
    deployContract(
      name: "IInitiaDEX",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IInitiaDEX>;
    deployContract(
      name: "IWeaveRewards",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IWeaveRewards>;
    deployContract(
      name: "WeaveVault",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.WeaveVault>;
    deployContract(
      name: "WeaveVesting",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.WeaveVesting>;
    deployContract(
      name: "IWeaveVault",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IWeaveVault>;
    deployContract(
      name: "WeaveZapIn",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.WeaveZapIn>;

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
  }
}
