/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as blackwingStrategySol from "./BlackwingStrategy.sol";
export type { blackwingStrategySol };
import type * as tucanaStrategySol from "./TucanaStrategy.sol";
export type { tucanaStrategySol };
export type { MockProtocol } from "./MockProtocol";
