/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface CrossMinitiaRouterInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "addMinitiaVault"
      | "depositToken"
      | "getTotalCrossMinitiaValue"
      | "harvestAll"
      | "mainVault"
      | "minitiaVaults"
      | "owner"
      | "rebalance"
      | "renounceOwnership"
      | "routeCapital"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AllHarvested"
      | "CapitalRouted"
      | "MinitiaVaultAdded"
      | "OwnershipTransferred"
      | "Rebalanced"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "addMinitiaVault",
    values: [string, AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "depositToken",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getTotalCrossMinitiaValue",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "harvestAll",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "mainVault", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "minitiaVaults",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "rebalance",
    values: [BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "routeCapital",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "addMinitiaVault",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "depositToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTotalCrossMinitiaValue",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "harvestAll", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "mainVault", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "minitiaVaults",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "rebalance", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "routeCapital",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
}

export namespace AllHarvestedEvent {
  export type InputTuple = [totalYield: BigNumberish];
  export type OutputTuple = [totalYield: bigint];
  export interface OutputObject {
    totalYield: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CapitalRoutedEvent {
  export type InputTuple = [totalAmount: BigNumberish];
  export type OutputTuple = [totalAmount: bigint];
  export interface OutputObject {
    totalAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MinitiaVaultAddedEvent {
  export type InputTuple = [
    name: string,
    strategy: AddressLike,
    chainId: BigNumberish,
    initialAllocation: BigNumberish
  ];
  export type OutputTuple = [
    name: string,
    strategy: string,
    chainId: bigint,
    initialAllocation: bigint
  ];
  export interface OutputObject {
    name: string;
    strategy: string;
    chainId: bigint;
    initialAllocation: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RebalancedEvent {
  export type InputTuple = [newAllocations: BigNumberish[]];
  export type OutputTuple = [newAllocations: bigint[]];
  export interface OutputObject {
    newAllocations: bigint[];
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface CrossMinitiaRouter extends BaseContract {
  connect(runner?: ContractRunner | null): CrossMinitiaRouter;
  waitForDeployment(): Promise<this>;

  interface: CrossMinitiaRouterInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  addMinitiaVault: TypedContractMethod<
    [
      name: string,
      strategy: AddressLike,
      chainId: BigNumberish,
      initialAllocation: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  depositToken: TypedContractMethod<[], [string], "view">;

  getTotalCrossMinitiaValue: TypedContractMethod<[], [bigint], "view">;

  harvestAll: TypedContractMethod<[], [bigint], "nonpayable">;

  mainVault: TypedContractMethod<[], [string], "view">;

  minitiaVaults: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, bigint, bigint, bigint, boolean] & {
        name: string;
        strategy: string;
        chainId: bigint;
        allocation: bigint;
        totalDeposited: bigint;
        active: boolean;
      }
    ],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  rebalance: TypedContractMethod<
    [newAllocations: BigNumberish[]],
    [void],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  routeCapital: TypedContractMethod<
    [totalAmount: BigNumberish],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "addMinitiaVault"
  ): TypedContractMethod<
    [
      name: string,
      strategy: AddressLike,
      chainId: BigNumberish,
      initialAllocation: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "depositToken"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getTotalCrossMinitiaValue"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "harvestAll"
  ): TypedContractMethod<[], [bigint], "nonpayable">;
  getFunction(
    nameOrSignature: "mainVault"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "minitiaVaults"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, bigint, bigint, bigint, boolean] & {
        name: string;
        strategy: string;
        chainId: bigint;
        allocation: bigint;
        totalDeposited: bigint;
        active: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "rebalance"
  ): TypedContractMethod<
    [newAllocations: BigNumberish[]],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "routeCapital"
  ): TypedContractMethod<[totalAmount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "AllHarvested"
  ): TypedContractEvent<
    AllHarvestedEvent.InputTuple,
    AllHarvestedEvent.OutputTuple,
    AllHarvestedEvent.OutputObject
  >;
  getEvent(
    key: "CapitalRouted"
  ): TypedContractEvent<
    CapitalRoutedEvent.InputTuple,
    CapitalRoutedEvent.OutputTuple,
    CapitalRoutedEvent.OutputObject
  >;
  getEvent(
    key: "MinitiaVaultAdded"
  ): TypedContractEvent<
    MinitiaVaultAddedEvent.InputTuple,
    MinitiaVaultAddedEvent.OutputTuple,
    MinitiaVaultAddedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "Rebalanced"
  ): TypedContractEvent<
    RebalancedEvent.InputTuple,
    RebalancedEvent.OutputTuple,
    RebalancedEvent.OutputObject
  >;

  filters: {
    "AllHarvested(uint256)": TypedContractEvent<
      AllHarvestedEvent.InputTuple,
      AllHarvestedEvent.OutputTuple,
      AllHarvestedEvent.OutputObject
    >;
    AllHarvested: TypedContractEvent<
      AllHarvestedEvent.InputTuple,
      AllHarvestedEvent.OutputTuple,
      AllHarvestedEvent.OutputObject
    >;

    "CapitalRouted(uint256)": TypedContractEvent<
      CapitalRoutedEvent.InputTuple,
      CapitalRoutedEvent.OutputTuple,
      CapitalRoutedEvent.OutputObject
    >;
    CapitalRouted: TypedContractEvent<
      CapitalRoutedEvent.InputTuple,
      CapitalRoutedEvent.OutputTuple,
      CapitalRoutedEvent.OutputObject
    >;

    "MinitiaVaultAdded(string,address,uint256,uint256)": TypedContractEvent<
      MinitiaVaultAddedEvent.InputTuple,
      MinitiaVaultAddedEvent.OutputTuple,
      MinitiaVaultAddedEvent.OutputObject
    >;
    MinitiaVaultAdded: TypedContractEvent<
      MinitiaVaultAddedEvent.InputTuple,
      MinitiaVaultAddedEvent.OutputTuple,
      MinitiaVaultAddedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "Rebalanced(uint256[])": TypedContractEvent<
      RebalancedEvent.InputTuple,
      RebalancedEvent.OutputTuple,
      RebalancedEvent.OutputObject
    >;
    Rebalanced: TypedContractEvent<
      RebalancedEvent.InputTuple,
      RebalancedEvent.OutputTuple,
      RebalancedEvent.OutputObject
    >;
  };
}
